// Builds src/geo.js: country outlines around Central Europe (decoded from a
// world-atlas TopoJSON file, Natural Earth data) plus the app's real venues
// and cities from data/venues.json.
//   node media/promo/tools/build-geo.mjs <path/to/countries-50m.json>
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const topo = JSON.parse(readFileSync(process.argv[2], "utf8"));
const world = JSON.parse(readFileSync(resolve(root, "data/venues.json"), "utf8"));

const BOX = { minLng: -12, maxLng: 34, minLat: 35, maxLat: 62 };
const [sx, sy] = topo.transform.scale;
const [tx, ty] = topo.transform.translate;

// Decode delta-encoded, quantized arcs into absolute [lng, lat].
const arcs = topo.arcs.map((arc) => {
  let x = 0;
  let y = 0;
  return arc.map(([dx, dy]) => {
    x += dx;
    y += dy;
    return [x * sx + tx, y * sy + ty];
  });
});
const arc = (i) => (i >= 0 ? arcs[i] : arcs[~i].slice().reverse());
const ring = (ids) => {
  const pts = [];
  ids.forEach((id, k) => pts.push(...arc(id).slice(k ? 1 : 0)));
  return pts;
};
const inBox = (r) => r.some(([x, y]) => x >= BOX.minLng && x <= BOX.maxLng && y >= BOX.minLat && y <= BOX.maxLat);
const simplify = (r, eps = 0.04) => {
  const out = [r[0]];
  for (const p of r.slice(1)) {
    const q = out[out.length - 1];
    if (Math.hypot(p[0] - q[0], p[1] - q[1]) >= eps) out.push(p);
  }
  return out.map(([x, y]) => [+x.toFixed(3), +y.toFixed(3)]);
};

const countries = [];
for (const g of topo.objects.countries.geometries) {
  const polys = g.type === "Polygon" ? [g.arcs] : g.type === "MultiPolygon" ? g.arcs : [];
  const rings = polys
    .map((p) => ring(p[0]))
    .filter(inBox)
    .map((r) => simplify(r))
    .filter((r) => r.length > 3);
  if (rings.length) countries.push({ name: g.properties?.name ?? g.id, rings });
}

const venues = world.venues.map(({ id, name, city, country, capacity, lat, lng }) => ({ id, name, city, country, capacity, lat, lng }));
const cities = world.cities.map(({ name, country, lat, lng }) => ({ name, country, lat, lng }));
const body = `// Generated by tools/build-geo.mjs. Outlines: Natural Earth via world-atlas@2.0.2 (public domain / ISC).\n// Venues and cities: data/venues.json.\nwindow.GEO = ${JSON.stringify({ countries, venues, cities })};\n`;
writeFileSync(resolve(here, "../src/geo.js"), body);
console.log(`countries ${countries.length}, rings ${countries.reduce((n, c) => n + c.rings.length, 0)}, venues ${venues.length}, ${(body.length / 1024).toFixed(0)} KB`);
